/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return capability and migration status */
        get: operations["getSystemRequirements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks visible to the authenticated principal */
        get: operations["listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one task projection */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted task events */
        get: operations["listTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream persisted task events incrementally
         * @description Server-Sent Events stream. Consumers resume with Last-Event-ID; each data field contains one TaskEvent JSON object. The P0 implementation tails the durable compatibility store and will move to NATS fan-out in P3.
         */
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List model providers without secret material */
        get: operations["listModelProviders"];
        put?: never;
        /** Create a model provider and optional write-only credential */
        post: operations["createModelProvider"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List provider readiness, circuit breaker, and recent demand signals */
        get: operations["listModelProviderHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{provider_id}/secret": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Rotate or revoke the write-only credential bound to a provider */
        put: operations["rotateModelProviderSecret"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{provider_id}/enabled": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enable or disable a provider without deleting its audit history */
        post: operations["setModelProviderEnabled"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/catalog": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List routable model instances and capabilities */
        get: operations["listModelCatalog"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a non-streaming model completion through the gateway */
        post: operations["createModelCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Stream a model completion through Server-Sent Events */
        post: operations["streamModelCompletion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/models/invocations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List model invocation ledger entries without prompt or response bodies */
        get: operations["listModelInvocations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve the authenticated user and effective permissions */
        get: operations["getEnterpriseSession"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tenants/current": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return the active tenant from the verified identity context */
        get: operations["getCurrentTenant"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/organizations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List organizations inside the effective tenant/project scope */
        get: operations["listOrganizations"];
        put?: never;
        /** Create an organization with an idempotent tenant-scoped command */
        post: operations["createOrganization"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List projects visible through tenant or project assignments */
        get: operations["listProjects"];
        put?: never;
        /** Create a project in the authenticated tenant */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/iam/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tenant identity bindings */
        get: operations["listTenantUsers"];
        put?: never;
        /** Provision an issuer/subject binding for an existing OIDC user */
        post: operations["provisionTenantUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/iam/roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List explicit roles and permission codes */
        get: operations["listTenantRoles"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/iam/role-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Grant a tenant- or project-scoped role assignment */
        post: operations["grantRoleAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/iam/role-assignments/{assignment_id}/revoke": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Revoke a role assignment immediately for subsequent requests */
        post: operations["revokeRoleAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/effective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resolve tenant, project, and user configuration precedence */
        get: operations["getEffectiveConfiguration"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config/{config_key}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Create or version-update one managed configuration entry */
        put: operations["putConfigurationEntry"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/audit/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List append-only audit events in the authorized data scope */
        get: operations["listEnterpriseAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            detail: string;
            code: string;
            /** Format: uuid */
            request_id: string | null;
            trace_id: string | null;
            errors?: {
                location: string[];
                message: string;
                type: string;
            }[];
        };
        SystemRequirements: {
            scope: string;
            implemented: {
                [key: string]: string;
            };
            p0_migration: {
                status: string;
                target: string;
                compatibility: string;
                legacy_execution_enabled: boolean;
            };
            excluded: string[];
        };
        Task: {
            /** Format: uuid */
            id: string;
            title: string;
            target: string;
            intent: string;
            indicators: string[];
            /** Format: uuid */
            scope_id: string;
            status: string;
            approval_status: string;
            /** Format: uuid */
            created_by: string;
            assigned_skills: string[];
            plan?: {
                [key: string]: unknown;
            } | null;
            result?: {
                [key: string]: unknown;
            } | null;
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TaskEvent: {
            id: number;
            event_type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
        PageMeta: {
            next_cursor: string | null;
            has_more: boolean;
            page_size: number;
        };
        ModelProviderCreate: {
            name: string;
            /** @enum {string} */
            kind: "mock" | "openai_compatible" | "ollama";
            /** Format: uri */
            base_url?: string | null;
            model: string;
            /** @description Accepted only on write. Never returned by any response. */
            api_key?: string | null;
            /** @default true */
            enabled: boolean;
            /** @default 100 */
            priority: number;
            /** @default 60 */
            rate_limit_per_minute: number;
            /** @default 100000 */
            token_quota_per_minute: number;
            /** @default 30 */
            timeout_seconds: number;
            /** @default 0 */
            input_cost_per_1k: number;
            /** @default 0 */
            output_cost_per_1k: number;
            capabilities?: string[];
            config?: {
                [key: string]: unknown;
            };
        };
        ModelProvider: {
            /** Format: uuid */
            id: string;
            name: string;
            /** @enum {string} */
            kind: "mock" | "openai_compatible" | "ollama";
            /** Format: uri */
            base_url: string | null;
            model: string;
            has_api_key: boolean;
            /** @description Non-secret reference to configured credential material. */
            credential_ref: string | null;
            enabled: boolean;
            priority: number;
            rate_limit_per_minute: number;
            token_quota_per_minute: number;
            timeout_seconds: number;
            input_cost_per_1k: number;
            output_cost_per_1k: number;
            capabilities: string[];
            config: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        ModelProviderHealth: {
            /** Format: uuid */
            provider_id: string;
            provider: string;
            model: string;
            enabled: boolean;
            /** @enum {string} */
            status: "ready" | "disabled" | "circuit_open";
            failure_count: number;
            circuit_open: boolean;
            circuit_retry_after_ms: number;
            recent_request_count: number;
        };
        ModelCatalogItem: {
            /** Format: uuid */
            provider_id: string;
            provider: string;
            /** @enum {string} */
            kind: "mock" | "openai_compatible" | "ollama";
            model: string;
            enabled: boolean;
            priority: number;
            capabilities: string[];
            input_cost_per_1k: number;
            output_cost_per_1k: number;
        };
        ModelChatMessage: {
            /** @enum {string} */
            role: "user" | "assistant";
            content: string;
        };
        ModelResponseFormat: {
            /**
             * @default text
             * @enum {string}
             */
            type: "text" | "json_object";
        };
        ModelToolDefinition: {
            name: string;
            description: string;
            /** @description JSON Schema object for tool input. Tool names are the invocation allow-list. */
            input_schema: {
                [key: string]: unknown;
            };
        };
        ModelCompletionRequest: {
            messages: components["schemas"]["ModelChatMessage"][];
            /**
             * @default planning
             * @enum {string}
             */
            purpose: "planning" | "summarization" | "reporting" | "tool_selection";
            /** @default 512 */
            max_tokens: number;
            response_format?: components["schemas"]["ModelResponseFormat"];
            tools?: components["schemas"]["ModelToolDefinition"][];
            /** @default false */
            stream: boolean;
        };
        ModelUsage: {
            prompt_tokens: number;
            completion_tokens: number;
            total_tokens: number;
        };
        ModelToolProtocol: {
            allowed_tools: string[];
            /** @description Tool calls emitted by a provider, constrained to allowed_tools. */
            tool_calls: {
                [key: string]: unknown;
            }[];
        };
        ModelCompletion: {
            /** Format: uuid */
            id: string;
            provider: string;
            model: string;
            purpose: string;
            content: string;
            /** @enum {string} */
            response_format: "text" | "json_object";
            tool_protocol: components["schemas"]["ModelToolProtocol"];
            usage: components["schemas"]["ModelUsage"];
            cost_usd: number;
            failover_count: number;
            latency_ms: number;
        };
        ModelInvocation: {
            /** Format: uuid */
            id: string;
            provider: string;
            model: string;
            purpose: string;
            /** @enum {string} */
            status: "succeeded" | "failed";
            usage: components["schemas"]["ModelUsage"];
            cost_usd: number;
            failover_count: number;
            structured_output: boolean;
            tool_count: number;
            latency_ms: number;
            error: string | null;
            /** Format: date-time */
            created_at: string;
        };
        Tenant: {
            /** Format: uuid */
            id: string;
            slug: string;
            display_name: string;
            /** @enum {string} */
            status: "ACTIVE" | "SUSPENDED" | "DISABLED";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        OrganizationCreate: {
            slug: string;
            display_name: string;
        };
        Organization: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            slug: string;
            display_name: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED" | "DISABLED";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        OrganizationPage: {
            items: components["schemas"]["Organization"][];
            page: components["schemas"]["PageMeta"];
        };
        ProjectCreate: {
            /** Format: uuid */
            organization_id?: string | null;
            slug: string;
            display_name: string;
        };
        Project: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            organization_id: string | null;
            slug: string;
            display_name: string;
            /** @enum {string} */
            status: "ACTIVE" | "ARCHIVED" | "DISABLED";
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        ProjectPage: {
            items: components["schemas"]["Project"][];
            page: components["schemas"]["PageMeta"];
        };
        UserProvisionCreate: {
            subject: string;
            username: string;
            /** Format: email */
            email?: string | null;
        };
        User: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uri */
            issuer: string;
            subject: string;
            username: string;
            /** Format: email */
            email: string | null;
            active: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        UserPage: {
            items: components["schemas"]["User"][];
            page: components["schemas"]["PageMeta"];
        };
        Role: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            code: string;
            display_name: string;
            description: string;
            /** @enum {string} */
            scope_type: "TENANT" | "PROJECT" | "BOTH";
            system_managed: boolean;
            permissions: string[];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        RolePage: {
            items: components["schemas"]["Role"][];
            page: components["schemas"]["PageMeta"];
        };
        RoleAssignmentCreate: {
            /** Format: uuid */
            user_id: string;
            role_code: string;
            /** Format: uuid */
            project_id?: string | null;
            reason: string;
            /** Format: date-time */
            expires_at?: string | null;
        };
        RoleAssignmentRevoke: {
            reason: string;
        };
        RoleAssignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            project_id: string | null;
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            role_id: string;
            role_code: string;
            /** Format: uuid */
            granted_by: string;
            reason: string;
            /** Format: date-time */
            starts_at: string;
            /** Format: date-time */
            expires_at: string | null;
            /** Format: date-time */
            revoked_at: string | null;
            /** Format: uuid */
            revoked_by: string | null;
            revocation_reason: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        ConfigEntryUpdate: {
            /** @enum {string} */
            scope_type: "TENANT" | "PROJECT" | "USER";
            /** Format: uuid */
            project_id?: string | null;
            /** Format: uuid */
            user_id?: string | null;
            value: unknown;
            expected_version?: number | null;
        };
        ConfigEntry: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            project_id: string | null;
            /** Format: uuid */
            user_id: string | null;
            /** @enum {string} */
            scope_type: "TENANT" | "PROJECT" | "USER";
            config_key: string;
            config_value: unknown;
            /** Format: uuid */
            created_by: string;
            /** Format: uuid */
            updated_by: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
            version: number;
        };
        EffectiveConfig: {
            values: {
                [key: string]: unknown;
            };
            sources: {
                [key: string]: "TENANT" | "PROJECT" | "USER";
            };
        };
        AuditEvent: {
            id: number;
            /** Format: uuid */
            event_id: string;
            /** Format: uuid */
            tenant_id: string;
            /** Format: uuid */
            project_id: string | null;
            actor_type: string;
            /** Format: uuid */
            actor_user_id: string | null;
            action: string;
            resource_type: string;
            resource_id: string;
            /** @enum {string} */
            outcome: "SUCCEEDED" | "FAILED" | "DENIED" | "CANCELLED";
            /** @enum {string} */
            risk_level: "R0" | "R1" | "R2" | "R3" | "R4";
            trace_id: string;
            /** Format: uuid */
            request_id: string;
            details: {
                [key: string]: unknown;
            };
            previous_hash: string;
            entry_hash: string;
            /** Format: date-time */
            occurred_at: string;
        };
        AuditEventPage: {
            items: components["schemas"]["AuditEvent"][];
            page: components["schemas"]["PageMeta"];
        };
        SessionProjectAccess: {
            /** Format: uuid */
            project_id: string;
            roles: string[];
            permissions: string[];
        };
        Session: {
            /** Format: uuid */
            user_id: string;
            /** Format: uuid */
            tenant_id: string;
            username: string;
            /** Format: email */
            email: string | null;
            tenant_status: string;
            roles: string[];
            permissions: string[];
            projects: components["schemas"]["SessionProjectAccess"][];
        };
    };
    responses: {
        /** @description Authentication is missing or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The principal lacks the required permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist or is outside the principal data scope */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Version, uniqueness, or idempotency conflict */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Input failed schema or managed-configuration validation */
        ValidationFailed: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description Provider request or token quota has been exceeded */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        XRequestId: string;
        TaskId: string;
        ProviderId: string;
        /** @description Resource selection only; never accepted as authorization proof. */
        XProjectId: string;
        IdempotencyKey: string;
        PageSize: number;
        Cursor: string;
        AssignmentId: string;
    };
    requestBodies: never;
    headers: {
        /** @description End-to-end request correlation identifier */
        XRequestId: string;
        /** @description Whether the response was replayed from a prior identical command. */
        IdempotencyReplayed: "true" | "false";
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemRequirements: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability status */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemRequirements"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task collection */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTaskEvents: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered event collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEvent"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Last-Event-ID"?: number;
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incremental task event stream with periodic keepalive comments */
            200: {
                headers: {
                    /** @description no-cache */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listModelProviders: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider collection */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProvider"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createModelProvider: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelProviderCreate"];
            };
        };
        responses: {
            /** @description Provider created without echoing secret values */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProvider"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listModelProviderHealth: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider health collection */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProviderHealth"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    rotateModelProviderSecret: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
                /** @description Write-only credential value. It is never returned by any API. */
                "X-Provider-API-Key"?: string;
            };
            path: {
                provider_id: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Credential metadata updated without returning secret material */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProvider"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    setModelProviderEnabled: {
        parameters: {
            query: {
                enabled: boolean;
            };
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                provider_id: components["parameters"]["ProviderId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider enabled state changed */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelProvider"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    listModelCatalog: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Model catalog */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCatalogItem"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createModelCompletion: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCompletionRequest"];
            };
        };
        responses: {
            /** @description Completion with usage, cost, and allowed tool metadata */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelCompletion"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    streamModelCompletion: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ModelCompletionRequest"];
            };
        };
        responses: {
            /** @description Completion chunks followed by final usage metadata */
            200: {
                headers: {
                    /** @description no-cache */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
            429: components["responses"]["TooManyRequests"];
        };
    };
    listModelInvocations: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Invocation ledger entries */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInvocation"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getEnterpriseSession: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-resolved identity and authorization context */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getCurrentTenant: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current tenant */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Tenant"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    listOrganizations: {
        parameters: {
            query?: {
                page_size?: components["parameters"]["PageSize"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Organization page */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OrganizationPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createOrganization: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizationCreate"];
            };
        };
        responses: {
            /** @description Organization created or replayed */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Organization"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listProjects: {
        parameters: {
            query?: {
                page_size?: components["parameters"]["PageSize"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                /** @description Resource selection only; never accepted as authorization proof. */
                "X-Project-ID"?: components["parameters"]["XProjectId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project page */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Project created or replayed */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listTenantUsers: {
        parameters: {
            query?: {
                page_size?: components["parameters"]["PageSize"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description User page */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    provisionTenantUser: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserProvisionCreate"];
            };
        };
        responses: {
            /** @description User binding provisioned or replayed */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listTenantRoles: {
        parameters: {
            query?: {
                page_size?: components["parameters"]["PageSize"];
                cursor?: components["parameters"]["Cursor"];
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Role page */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RolePage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    grantRoleAssignment: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignmentCreate"];
            };
        };
        responses: {
            /** @description Assignment granted or replayed */
            201: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    revokeRoleAssignment: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                assignment_id: components["parameters"]["AssignmentId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoleAssignmentRevoke"];
            };
        };
        responses: {
            /** @description Assignment revoked or replayed */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoleAssignment"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            404: components["responses"]["NotFound"];
            409: components["responses"]["Conflict"];
        };
    };
    getEffectiveConfiguration: {
        parameters: {
            query?: {
                project_id?: string;
                user_id?: string;
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Effective configuration and source layer for each key */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EffectiveConfig"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    putConfigurationEntry: {
        parameters: {
            query?: never;
            header: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Idempotency-Key": components["parameters"]["IdempotencyKey"];
            };
            path: {
                config_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigEntryUpdate"];
            };
        };
        responses: {
            /** @description Configuration entry created, updated, or replayed */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    "Idempotency-Replayed": components["headers"]["IdempotencyReplayed"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigEntry"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
            409: components["responses"]["Conflict"];
            422: components["responses"]["ValidationFailed"];
        };
    };
    listEnterpriseAuditEvents: {
        parameters: {
            query?: {
                page_size?: components["parameters"]["PageSize"];
                cursor?: components["parameters"]["Cursor"];
                project_id?: string;
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Audit event page */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuditEventPage"];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
}
