/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/system/requirements": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Return capability and migration status */
        get: operations["getSystemRequirements"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List tasks visible to the authenticated principal */
        get: operations["listTasks"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get one task projection */
        get: operations["getTask"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List persisted task events */
        get: operations["listTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tasks/{task_id}/events/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream persisted task events incrementally
         * @description Server-Sent Events stream. Consumers resume with Last-Event-ID; each data field contains one TaskEvent JSON object. The P0 implementation tails the durable compatibility store and will move to NATS fan-out in P3.
         */
        get: operations["streamTaskEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Problem: {
            detail: string;
            code?: string | null;
            request_id?: string | null;
        };
        SystemRequirements: {
            scope: string;
            implemented: {
                [key: string]: string;
            };
            p0_migration: {
                status: string;
                target: string;
                compatibility: string;
                legacy_execution_enabled: boolean;
            };
            excluded: string[];
        };
        Task: {
            /** Format: uuid */
            id: string;
            title: string;
            target: string;
            intent: string;
            indicators: string[];
            /** Format: uuid */
            scope_id: string;
            status: string;
            approval_status: string;
            /** Format: uuid */
            created_by: string;
            assigned_skills: string[];
            plan?: {
                [key: string]: unknown;
            } | null;
            result?: {
                [key: string]: unknown;
            } | null;
            error?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at: string;
        };
        TaskEvent: {
            id: number;
            event_type: string;
            payload: {
                [key: string]: unknown;
            };
            /** Format: date-time */
            created_at: string;
        };
    };
    responses: {
        /** @description Authentication is missing or invalid */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The principal lacks the required permission */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
        /** @description The resource does not exist or is outside the principal data scope */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        XRequestId: string;
        TaskId: string;
    };
    requestBodies: never;
    headers: {
        /** @description End-to-end request correlation identifier */
        XRequestId: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getSystemRequirements: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Capability status */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemRequirements"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listTasks: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task collection */
            200: {
                headers: {
                    "X-Request-ID": components["headers"]["XRequestId"];
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            403: components["responses"]["Forbidden"];
        };
    };
    getTask: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Task projection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    listTaskEvents: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ordered event collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TaskEvent"][];
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
    streamTaskEvents: {
        parameters: {
            query?: never;
            header?: {
                "X-Request-ID"?: components["parameters"]["XRequestId"];
                "Last-Event-ID"?: number;
            };
            path: {
                task_id: components["parameters"]["TaskId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Incremental task event stream with periodic keepalive comments */
            200: {
                headers: {
                    /** @description no-cache */
                    "Cache-Control"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
            401: components["responses"]["Unauthorized"];
            404: components["responses"]["NotFound"];
        };
    };
}
