import type { components, operations, paths } from './api.generated';

export type { components, operations, paths };

export type Task = components['schemas']['Task'];
export type TaskEvent = components['schemas']['TaskEvent'];
export type TaskExecution = components['schemas']['TaskExecution'];
export type SystemRequirements = components['schemas']['SystemRequirements'];
export type EnterpriseSession = components['schemas']['Session'];
export type Tenant = components['schemas']['Tenant'];
export type Organization = components['schemas']['Organization'];
export type Project = components['schemas']['Project'];
export type EnterpriseUser = components['schemas']['User'];
export type EnterpriseRole = components['schemas']['Role'];
export type RoleAssignment = components['schemas']['RoleAssignment'];
export type AuditEvent = components['schemas']['AuditEvent'];
export type AgentDefinition = components['schemas']['AgentDefinition'];
export type WorkflowDefinition = components['schemas']['WorkflowDefinition'];
export type SkillDefinition = components['schemas']['SkillDefinition'];
export type ModelProvider = components['schemas']['ModelProvider'];
export type ModelProviderHealth = components['schemas']['ModelProviderHealth'];
export type ModelCatalogItem = components['schemas']['ModelCatalogItem'];
export type ModelInvocation = components['schemas']['ModelInvocation'];
export type EvidenceItem = components['schemas']['EvidenceItem'];
export type RAGDocument = components['schemas']['RAGDocument'];
export type RAGDocumentCreate = components['schemas']['RAGDocumentCreate'];
export type RAGSearchRequest = components['schemas']['RAGSearchRequest'];
export type RAGSearchResponse = components['schemas']['RAGSearchResponse'];
export type PolicyEvaluationRequest = components['schemas']['PolicyEvaluationRequest'];
export type PolicyDecision = components['schemas']['PolicyDecision'];
export type ValidationPlan = components['schemas']['ValidationPlan'];
export type ValidationPlanCreate = components['schemas']['ValidationPlanCreate'];
export type ValidationPlanReview = components['schemas']['ValidationPlanReview'];
export type ValidationProbeStep = components['schemas']['ValidationProbeStep'];
