import type { components, operations, paths } from './api.generated';

export type { components, operations, paths };

export type Task = components['schemas']['Task'];
export type TaskEvent = components['schemas']['TaskEvent'];
export type TaskExecution = components['schemas']['TaskExecution'];
export type SystemRequirements = components['schemas']['SystemRequirements'];
export type SystemResilience = components['schemas']['SystemResilienceResponse'];
export type EvidenceConsistencyCheck =
  components['schemas']['EvidenceConsistencyCheckRequest'];
export type EvidenceConsistencyReport =
  components['schemas']['EvidenceConsistencyReportResponse'];
export type EnterpriseSession = components['schemas']['Session'];
export type Tenant = components['schemas']['Tenant'];
export type Organization = components['schemas']['Organization'];
export type Project = components['schemas']['Project'];
export type EnterpriseUser = components['schemas']['User'];
export type EnterpriseRole = components['schemas']['Role'];
export type RoleAssignment = components['schemas']['RoleAssignment'];
export type AuditEvent = components['schemas']['AuditEvent'];
export type AgentDefinition = components['schemas']['AgentDefinition'];
export type WorkflowDefinition = components['schemas']['WorkflowDefinition'];
export type SkillDefinition = components['schemas']['SkillDefinition'];
export type ModelProvider = components['schemas']['ModelProvider'];
export type ModelProviderHealth = components['schemas']['ModelProviderHealth'];
export type ModelCatalogItem = components['schemas']['ModelCatalogItem'];
export type ModelInvocation = components['schemas']['ModelInvocation'];
export type EvidenceItem = components['schemas']['EvidenceItem'];
export type RAGDocument = components['schemas']['RAGDocument'];
export type RAGDocumentCreate = components['schemas']['RAGDocumentCreate'];
export type RAGSearchRequest = components['schemas']['RAGSearchRequest'];
export type RAGSearchResponse = components['schemas']['RAGSearchResponse'];
export type PolicyEvaluationRequest = components['schemas']['PolicyEvaluationRequest'];
export type PolicyDecision = components['schemas']['PolicyDecision'];
export type ValidationPlan = components['schemas']['ValidationPlan'];
export type ValidationPlanCreate = components['schemas']['ValidationPlanCreate'];
export type ValidationPlanReview = components['schemas']['ValidationPlanReview'];
export type ValidationProbeStep = components['schemas']['ValidationProbeStep'];
export type ValidationExecution = components['schemas']['ValidationExecution'];
export type ValidationExecutionCreate = components['schemas']['ValidationExecutionCreate'];
export type ValidationExecutionEvent = components['schemas']['ValidationExecutionEvent'];
export type ValidationExecutionEvidence = components['schemas']['ValidationExecutionEvidence'];
export type ValidationExecutionReview = components['schemas']['ValidationExecutionReview'];
export type ValidationTemplate = components['schemas']['ValidationTemplate'];
export type VulnerabilityCase = components['schemas']['VulnerabilityCase'];
export type VulnerabilityCaseCreate = components['schemas']['VulnerabilityCaseCreate'];
export type VulnerabilityCasePatch = components['schemas']['VulnerabilityCasePatch'];
export type VulnerabilityCaseDetail = components['schemas']['VulnerabilityCaseDetail'];
export type CaseFinding = components['schemas']['CaseFinding'];
export type CaseFindingCreate = components['schemas']['CaseFindingCreate'];
export type RemediationProposal = components['schemas']['RemediationProposal'];
export type RemediationProposalCreate = components['schemas']['RemediationProposalCreate'];
export type RemediationDecision = components['schemas']['RemediationDecision'];
export type RemediationDecisionCreate = components['schemas']['RemediationDecisionCreate'];
export type RemediationImplementation = components['schemas']['RemediationImplementation'];
export type RemediationImplementationCreate = components['schemas']['RemediationImplementationCreate'];
export type RetestRequest = components['schemas']['RetestRequest'];
export type RetestRequestCreate = components['schemas']['RetestRequestCreate'];
export type ValidationComparison = components['schemas']['ValidationComparison'];
export type CaseDisposition = components['schemas']['CaseDisposition'];
export type CaseDispositionCreate = components['schemas']['CaseDispositionCreate'];
export type CaseCloseRequest = components['schemas']['CaseCloseRequest'];
export type CaseReport = components['schemas']['CaseReport'];
export type CaseReportCreate = components['schemas']['CaseReportCreate'];
export type EvaluationSuiteCreate = components['schemas']['EvaluationSuiteCreate'];
export type EvaluationSuite = components['schemas']['EvaluationSuiteResponse'];
export type EvaluationDatasetCreate = components['schemas']['EvaluationDatasetCreate'];
export type EvaluationDataset = components['schemas']['EvaluationDatasetDetailResponse'];
export type EvaluationCaseCreate = components['schemas']['EvaluationCaseCreate'];
export type EvaluationCase = components['schemas']['EvaluationCaseResponse'];
export type EvaluationCaseOutput = components['schemas']['EvaluationCaseOutput'];
export type EvaluationRunCreate = components['schemas']['EvaluationRunCreate'];
export type EvaluationRun = components['schemas']['EvaluationRunResponse'];
export type EvaluationRunDetail = components['schemas']['EvaluationRunDetailResponse'];
export type EvaluationRunVariantCreate =
  components['schemas']['EvaluationRunVariantCreate'];
export type EvaluationRunVariant = components['schemas']['EvaluationRunVariantResponse'];
export type EvaluationResult = components['schemas']['EvaluationResultResponse'];
export type MetricResult = components['schemas']['MetricResultResponse'];
export type EvaluationFailure = components['schemas']['EvaluationFailureResponse'];
export type EvaluationComparisonCreate =
  components['schemas']['EvaluationComparisonCreate'];
export type EvaluationComparison = components['schemas']['EvaluationComparisonResponse'];
export type EvaluationReviewCreate = components['schemas']['EvaluationReviewCreate'];
export type EvaluationReview = components['schemas']['EvaluationReviewResponse'];
export type PromotionDecisionCreate = components['schemas']['PromotionDecisionCreate'];
export type PromotionDecision = components['schemas']['PromotionDecisionResponse'];
export type ReleaseArtifactCreate = components['schemas']['ReleaseArtifactCreate'];
export type ReleaseArtifact = components['schemas']['ReleaseArtifactResponse'];
export type ReleaseArtifactDetail = components['schemas']['ReleaseArtifactDetailResponse'];
export type ReleaseCandidateCreate = components['schemas']['ReleaseCandidateCreate'];
export type ReleaseCandidate = components['schemas']['ReleaseCandidateResponse'];
export type ReleaseCandidateDetail = components['schemas']['ReleaseCandidateDetailResponse'];
export type ReleaseGateEvaluationRequest =
  components['schemas']['ReleaseGateEvaluationRequest'];
export type ReleaseGateResult = components['schemas']['ReleaseGateResultResponse'];
export type ReleaseApprovalCreate = components['schemas']['ReleaseApprovalCreate'];
export type ReleaseApproval = components['schemas']['ReleaseApprovalResponse'];
export type ReleaseExceptionCreate = components['schemas']['ReleaseExceptionCreate'];
export type ReleaseException = components['schemas']['ReleaseExceptionResponse'];
export type EnvironmentPromotionCreate =
  components['schemas']['EnvironmentPromotionCreate'];
export type EnvironmentPromotionResult =
  components['schemas']['EnvironmentPromotionResultResponse'];
export type DeploymentRecord = components['schemas']['DeploymentRecordResponse'];
export type RollbackCreate = components['schemas']['RollbackCreate'];
export type RollbackRecord = components['schemas']['RollbackRecordResponse'];
export type DriftDetectionResult = components['schemas']['DriftDetectionResultResponse'];
export type CompliancePackage = components['schemas']['CompliancePackageResponse'];
export type RequirementTraceabilityItem = components['schemas']['RequirementTraceabilityItem'];
export type ProductionGate = components['schemas']['ProductionGateResponse'];
export type AcceptanceStatus = components['schemas']['AcceptanceStatusResponse'];
export type ProductionReadiness = components['schemas']['ProductionReadinessResponse'];
export type AcceptanceRunCreate = components['schemas']['AcceptanceRunCreate'];
export type AcceptanceRun = components['schemas']['AcceptanceRunResponse'];
export type DeliveryPackageCreate = components['schemas']['DeliveryPackageCreate'];
export type DeliveryPackage = components['schemas']['DeliveryPackageResponse'];
export type ComplianceControl = components['schemas']['ComplianceControlResponse'];
export type ComplianceEvidencePackageCreate =
  components['schemas']['ComplianceEvidencePackageCreate'];
export type ComplianceEvidencePackage =
  components['schemas']['ComplianceEvidencePackageResponse'];
export type DataExportCreate = components['schemas']['DataExportCreate'];
export type DataExport = components['schemas']['DataExportResponse'];
export type DataDeletionRequestCreate = components['schemas']['DataDeletionRequestCreate'];
export type DataDeletionRequest = components['schemas']['DataDeletionRequestResponse'];
export type LegalHoldCreate = components['schemas']['LegalHoldCreate'];
export type LegalHold = components['schemas']['LegalHoldResponse'];
