apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "vulnlab.fullname" . }}-web-console
  labels:
    {{- include "vulnlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-console
spec:
  {{- if not .Values.webConsole.autoscaling.enabled }}
  replicas: {{ .Values.webConsole.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "vulnlab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web-console
  template:
    metadata:
      annotations:
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "vulnlab.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web-console
    spec:
      serviceAccountName: {{ include "vulnlab.serviceAccountName" . }}
      automountServiceAccountToken: false
      securityContext:
        runAsNonRoot: true
        runAsUser: 101
        runAsGroup: 101
        fsGroup: 101
        seccompProfile:
          type: RuntimeDefault
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: web-console
          image: "{{ .Values.webConsole.image.repository }}:{{ .Values.webConsole.image.tag }}"
          imagePullPolicy: {{ .Values.global.imagePullPolicy }}
          ports:
            - name: http
              containerPort: 8080
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            capabilities:
              drop: ["ALL"]
          resources:
            {{- toYaml .Values.webConsole.resources | nindent 12 }}
          volumeMounts:
            - name: tmp
              mountPath: /tmp
            - name: nginx-cache
              mountPath: /var/cache/nginx
            - name: nginx-run
              mountPath: /var/run
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
        - name: nginx-cache
          emptyDir:
            medium: Memory
            sizeLimit: 16Mi
        - name: nginx-run
          emptyDir:
            medium: Memory
            sizeLimit: 1Mi
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
