{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vulnlab.fullname" . }}-gateway-ingress
  labels:
    {{- include "vulnlab.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "vulnlab.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: gateway
  policyTypes: [Ingress]
  ingress:
    - ports:
        - port: 8080
          protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "vulnlab.fullname" . }}-internal-ingress
  labels:
    {{- include "vulnlab.labels" . | nindent 4 }}
spec:
  podSelector:
    matchExpressions:
      - key: app.kubernetes.io/component
        operator: In
        values: [web-console, control-plane]
  policyTypes: [Ingress]
  ingress:
    - from:
        - podSelector:
            matchLabels:
              {{- include "vulnlab.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: gateway
      ports:
        - port: 8080
          protocol: TCP
        - port: 8000
          protocol: TCP
{{- end }}
