{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vulnlab.secretName" . }}
  labels:
    {{- include "vulnlab.labels" . | nindent 4 }}
type: Opaque
stringData:
  VULNLAB_ADMIN_KEY: {{ required "secrets.adminKey is required when secrets.create=true" .Values.secrets.adminKey | quote }}
  VULNLAB_MASTER_KEY: {{ required "secrets.masterKey is required when secrets.create=true" .Values.secrets.masterKey | quote }}
{{- end }}
