apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulnlab.fullname" . }}-gateway
  labels:
    {{- include "vulnlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
spec:
  type: {{ .Values.gateway.service.type }}
  selector:
    {{- include "vulnlab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: gateway
  ports:
    - name: http
      port: {{ .Values.gateway.service.port }}
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulnlab.fullname" . }}-web-console
  labels:
    {{- include "vulnlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: web-console
spec:
  type: ClusterIP
  selector:
    {{- include "vulnlab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: web-console
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vulnlab.fullname" . }}-control-plane
  labels:
    {{- include "vulnlab.labels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
spec:
  type: ClusterIP
  selector:
    {{- include "vulnlab.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: control-plane
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
