BEGIN;

GRANT DELETE ON ALL TABLES IN SCHEMA iam TO vulnlab_app;
GRANT DELETE ON ALL TABLES IN SCHEMA control TO vulnlab_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA iam
    GRANT DELETE ON TABLES TO vulnlab_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA control
    GRANT DELETE ON TABLES TO vulnlab_app;

COMMIT;
