BEGIN;

REVOKE DELETE ON ALL TABLES IN SCHEMA iam FROM vulnlab_app;
REVOKE DELETE ON ALL TABLES IN SCHEMA control FROM vulnlab_app;

ALTER DEFAULT PRIVILEGES IN SCHEMA iam
    REVOKE DELETE ON TABLES FROM vulnlab_app;
ALTER DEFAULT PRIVILEGES IN SCHEMA control
    REVOKE DELETE ON TABLES FROM vulnlab_app;

COMMIT;
